<?php

declare(strict_types=1);

return [
    [
        'group' => 'system',
        'method' => 'GET',
        'path' => '/ok',
        'controller' => StatusController::class,
        'action' => 'ok',
        'middleware' => [],
    ],
    [
        'group' => 'system',
        'method' => 'GET',
        'path' => '/api/health',
        'controller' => StatusController::class,
        'action' => 'ok',
        'middleware' => [],
    ],
    [
        'group' => 'system',
        'method' => 'POST',
        'path' => '/api/validate-demo',
        'controller' => PayloadController::class,
        'action' => 'validateDemo',
        'middleware' => [],
    ],

    // Auth routes: public login/register entry points plus protected logout.
    [
        'group' => 'auth',
        'method' => 'GET',
        'path' => '/auth/login',
        'controller' => AuthController::class,
        'action' => 'showLogin',
        'middleware' => [],
    ],
    [
        'group' => 'auth',
        'method' => 'POST',
        'path' => '/auth/login',
        'controller' => AuthController::class,
        'action' => 'login',
        'middleware' => ['validate:auth_login'],
    ],
    [
        'group' => 'auth',
        'method' => 'GET',
        'path' => '/auth/register',
        'controller' => AuthController::class,
        'action' => 'showRegister',
        'middleware' => [],
    ],
    [
        'group' => 'auth',
        'method' => 'POST',
        'path' => '/auth/register',
        'controller' => AuthController::class,
        'action' => 'register',
        'middleware' => ['validate:auth_register'],
    ],
    [
        'group' => 'auth',
        'method' => 'POST',
        'path' => '/auth/logout',
        'controller' => AuthController::class,
        'action' => 'logout',
        'middleware' => ['auth'],
    ],

    // Request routes: customer request creation, browsing, detail, and provider completion.
    [
        'group' => 'requests',
        'method' => 'GET',
        'path' => '/requests/browse',
        'controller' => RequestController::class,
        'action' => 'browse',
        'middleware' => [],
    ],
    [
        'group' => 'requests',
        'method' => 'GET',
        'path' => '/requests/{request_id}',
        'controller' => RequestController::class,
        'action' => 'show',
        'middleware' => ['auth'],
    ],
    [
        'group' => 'requests',
        'method' => 'POST',
        'path' => '/requests/create',
        'controller' => RequestController::class,
        'action' => 'create',
        'middleware' => ['auth', 'role:customer', 'validate:request_create'],
    ],
    [
        'group' => 'requests',
        'method' => 'PATCH',
        'path' => '/requests/{request_id}/complete',
        'controller' => RequestController::class,
        'action' => 'markCompleted',
        'middleware' => ['auth', 'role:provider', 'validate:request_complete'],
    ],

    // Offer routes: provider offers and customer negotiation actions.
    [
        'group' => 'offers',
        'method' => 'POST',
        'path' => '/offers/submit',
        'controller' => OfferController::class,
        'action' => 'submit',
        'middleware' => ['auth', 'role:provider', 'validate:offer_submit'],
    ],
    [
        'group' => 'offers',
        'method' => 'PATCH',
        'path' => '/offers/{offer_id}/accept',
        'controller' => OfferController::class,
        'action' => 'accept',
        'middleware' => ['auth', 'role:customer', 'validate:offer_accept'],
    ],
    [
        'group' => 'offers',
        'method' => 'PATCH',
        'path' => '/offers/{offer_id}/reject',
        'controller' => OfferController::class,
        'action' => 'reject',
        'middleware' => ['auth', 'role:customer', 'validate:offer_reject'],
    ],
    [
        'group' => 'offers',
        'method' => 'PATCH',
        'path' => '/offers/{offer_id}/counter',
        'controller' => OfferController::class,
        'action' => 'counter',
        'middleware' => ['auth', 'role:customer', 'validate:offer_counter'],
    ],

    // Review routes: customer review submission and provider review browsing.
    [
        'group' => 'reviews',
        'method' => 'POST',
        'path' => '/reviews/submit',
        'controller' => ReviewController::class,
        'action' => 'submit',
        'middleware' => ['auth', 'role:customer', 'validate:review_submit'],
    ],
    [
        'group' => 'reviews',
        'method' => 'GET',
        'path' => '/reviews/provider/{provider_id}',
        'controller' => ReviewController::class,
        'action' => 'providerReviews',
        'middleware' => [],
    ],

    // Admin routes: protected admin-only operational routes.
    [
        'group' => 'admin',
        'method' => 'GET',
        'path' => '/admin/dashboard',
        'controller' => AdminController::class,
        'action' => 'dashboard',
        'middleware' => ['auth', 'role:admin'],
    ],
    [
        'group' => 'admin',
        'method' => 'GET',
        'path' => '/admin/categories',
        'controller' => AdminController::class,
        'action' => 'categories',
        'middleware' => ['auth', 'role:admin'],
    ],
    [
        'group' => 'admin',
        'method' => 'POST',
        'path' => '/admin/categories',
        'controller' => AdminController::class,
        'action' => 'createCategory',
        'middleware' => ['auth', 'role:admin', 'validate:category_create'],
    ],
    [
        'group' => 'admin',
        'method' => 'PATCH',
        'path' => '/admin/categories/{category_id}',
        'controller' => AdminController::class,
        'action' => 'updateCategory',
        'middleware' => ['auth', 'role:admin', 'validate:category_update'],
    ],
    [
        'group' => 'admin',
        'method' => 'GET',
        'path' => '/admin/audit-logs',
        'controller' => AdminController::class,
        'action' => 'auditLogs',
        'middleware' => ['auth', 'role:admin'],
    ],
    [
        'group' => 'admin',
        'method' => 'PATCH',
        'path' => '/admin/providers/{provider_id}/verify',
        'controller' => AdminController::class,
        'action' => 'verifyProvider',
        'middleware' => ['auth', 'role:admin', 'validate:provider_verify'],
    ],
];
