-- Secure Local Service Marketplace schema for MySQL 8+
-- Includes database setup, tables, constraints, and views.

-- Drop schema if it exists
DROP DATABASE IF EXISTS market_place;
CREATE DATABASE market_place;
USE market_place;

-- Create application user
CREATE USER 'market'@'localhost' IDENTIFIED BY 'market';
GRANT ALL PRIVILEGES ON market_place.* TO 'market'@'localhost';

-- Enum types for status and role fields
-- MySQL ENUMs are defined inline in table definitions

-- Table definitions
CREATE TABLE USERS (
    USER_ID CHAR(36) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE ENUM('Customer', 'Provider', 'Admin') NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    LOCATION VARCHAR(255),
    RATING_AVERAGE DECIMAL(3, 2) DEFAULT 0.00,
    TOTAL_REVIEWS INT DEFAULT 0,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE SERVICE_CATEGORIES (
    CATEGORY_ID CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    ICON VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE SERVICE_REQUESTS (
    REQUEST_ID CHAR(36) PRIMARY KEY,
    CUSTOMER_ID CHAR(36) NOT NULL,
    CATEGORY_ID CHAR(36) NOT NULL,
    TITLE VARCHAR(160),
    DESCRIPTION TEXT NOT NULL,
    BUDGET DECIMAL(10, 2),
    PREFERRED_DATE DATE,
    STATUS ENUM('Requested', 'Negotiating', 'Assigned', 'Completed', 'Reviewed') NOT NULL DEFAULT 'Requested',
    LOCATION VARCHAR(255) NOT NULL,
    ACCEPTED_OFFER_ID CHAR(36),
    COMPLETION_PHOTO VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_SERVICE_REQUESTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SERVICE_REQUESTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES SERVICE_CATEGORIES (CATEGORY_ID) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE OFFERS (
    OFFER_ID CHAR(36) PRIMARY KEY,
    REQUEST_ID CHAR(36) NOT NULL,
    PROVIDER_ID CHAR(36) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    MESSAGE TEXT,
    STATUS ENUM('Pending', 'Accepted', 'Rejected', 'Countered') NOT NULL DEFAULT 'Pending',
    COUNTER_PRICE DECIMAL(10, 2),
    COUNTER_MESSAGE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_OFFERS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_OFFERS_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT UNIQUE_PROVIDER_REQUEST UNIQUE (REQUEST_ID, PROVIDER_ID)
) ENGINE=InnoDB;

ALTER TABLE SERVICE_REQUESTS
ADD CONSTRAINT FK_SERVICE_REQUESTS_ACCEPTED_OFFER FOREIGN KEY (ACCEPTED_OFFER_ID) REFERENCES OFFERS (OFFER_ID) ON DELETE SET NULL;

CREATE TABLE REVIEWS (
    REVIEW_ID CHAR(36) PRIMARY KEY,
    REQUEST_ID CHAR(36) NOT NULL UNIQUE,
    CUSTOMER_ID CHAR(36) NOT NULL,
    PROVIDER_ID CHAR(36) NOT NULL,
    RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
    COMMENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_REVIEWS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REVIEWS_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE AUDIT_LOGS (
    AUDIT_ID CHAR(36) PRIMARY KEY,
    USER_ID CHAR(36),
    ACTION VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID CHAR(36),
    DETAILS TEXT,
    IP_ADDRESS VARCHAR(45),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_AUDIT_LOGS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE STATUS_HISTORY (
    STATUS_HISTORY_ID CHAR(36) PRIMARY KEY,
    REQUEST_ID CHAR(36) NOT NULL,
    OLD_STATUS ENUM('Requested', 'Negotiating', 'Assigned', 'Completed', 'Reviewed'),
    NEW_STATUS ENUM('Requested', 'Negotiating', 'Assigned', 'Completed', 'Reviewed') NOT NULL,
    DURATION_SECONDS INT,
    CHANGED_BY CHAR(36),
    NOTES TEXT,
    CHANGED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_STATUS_HISTORY_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STATUS_HISTORY_CHANGED_BY FOREIGN KEY (CHANGED_BY) REFERENCES USERS (USER_ID) ON DELETE SET NULL
) ENGINE=InnoDB;

-- New Table: Notifications
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID CHAR(36) PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    TYPE VARCHAR(50) DEFAULT 'general',
    MESSAGE TEXT NOT NULL,
    LINK VARCHAR(500),
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID CHAR(36),
    IS_READ BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PASSWORD_RESETS (
    RESET_ID CHAR(36) PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    TOKEN_HASH CHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED_AT TIMESTAMP NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PASSWORD_RESETS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX IDX_USERS_ROLE ON USERS (ROLE);
CREATE INDEX IDX_USERS_LOCATION ON USERS (LOCATION);
CREATE INDEX IDX_SERVICE_REQUESTS_STATUS ON SERVICE_REQUESTS (STATUS);
CREATE INDEX IDX_SERVICE_REQUESTS_CATEGORY ON SERVICE_REQUESTS (CATEGORY_ID);
CREATE INDEX IDX_SERVICE_REQUESTS_CUSTOMER ON SERVICE_REQUESTS (CUSTOMER_ID);
CREATE INDEX IDX_OFFERS_REQUEST ON OFFERS (REQUEST_ID);
CREATE INDEX IDX_OFFERS_PROVIDER ON OFFERS (PROVIDER_ID);
CREATE INDEX IDX_OFFERS_STATUS ON OFFERS (STATUS);
CREATE INDEX IDX_REVIEWS_PROVIDER ON REVIEWS (PROVIDER_ID);
CREATE INDEX IDX_AUDIT_LOGS_ACTION ON AUDIT_LOGS (ACTION);
CREATE INDEX IDX_STATUS_HISTORY_REQUEST ON STATUS_HISTORY (REQUEST_ID);
CREATE INDEX IDX_NOTIFICATIONS_USER_READ ON NOTIFICATIONS (USER_ID, IS_READ);
CREATE INDEX IDX_PASSWORD_RESETS_TOKEN ON PASSWORD_RESETS (TOKEN_HASH);

-- Recommendations:
-- 1. Add indexes to frequently queried columns (e.g., EMAIL in USERS, STATUS in SERVICE_REQUESTS).
-- 2. Consider partitioning large tables (e.g., SERVICE_REQUESTS) by date or status for better performance.
-- 3. Add a table for direct messaging between users if needed.
