-- Secure Local Service Marketplace schema for PostgreSQL 13+
-- Includes database setup, tables, constraints, and views.
-- Create application role and database.
DROP SCHEMA IF EXISTS marketplace CASCADE;

CREATE ROLE market WITH LOGIN PASSWORD 'market';
CREATE DATABASE market_place OWNER market;

-- Create a tablespace inside the project directory
CREATE TABLESPACE market_place OWNER market LOCATION 'c:/xampp/htdocs/Market_Place_Web_Dev_Project/storage/tablespace';
SET default_tablespace = market_place;

-- Enable UUID generation.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enum types for status and role fields.
CREATE TYPE user_role AS ENUM ('Customer', 'Provider', 'Admin');
CREATE TYPE request_status AS ENUM ('Requested', 'Negotiating', 'Assigned', 'Completed', 'Reviewed');
CREATE TYPE offer_status AS ENUM ('Pending', 'Accepted', 'Rejected', 'Countered');

-- Create schema for organizing tables
CREATE SCHEMA IF NOT EXISTS marketplace AUTHORIZATION admin;

-- Set the search path to use the schema
SET search_path TO marketplace;

-- Table definitions
CREATE TABLE MARKETPLACE.USERS (
	USER_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
	ROLE USER_ROLE NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	PHONE VARCHAR(20),
	LOCATION VARCHAR(255),
	RATING_AVERAGE DECIMAL(3, 2) DEFAULT 0.00,
	TOTAL_REVIEWS INT DEFAULT 0,
	IS_VERIFIED BOOLEAN DEFAULT FALSE,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	UPDATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE MARKETPLACE.SERVICE_CATEGORIES (
	CATEGORY_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	NAME VARCHAR(100) NOT NULL UNIQUE,
	DESCRIPTION TEXT,
	ICON VARCHAR(50),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE MARKETPLACE.SERVICE_REQUESTS (
	REQUEST_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	CUSTOMER_ID UUID NOT NULL,
	CATEGORY_ID UUID NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PREFERRED_DATE DATE,
	STATUS REQUEST_STATUS NOT NULL DEFAULT 'Requested',
	LOCATION VARCHAR(255) NOT NULL,
	ACCEPTED_OFFER_ID UUID,
	COMPLETION_PHOTO VARCHAR(500),
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT FK_SERVICE_REQUESTS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_SERVICE_REQUESTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MARKETPLACE.SERVICE_CATEGORIES (CATEGORY_ID) ON DELETE RESTRICT
);

CREATE TABLE MARKETPLACE.OFFERS (
	OFFER_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	REQUEST_ID UUID NOT NULL,
	PROVIDER_ID UUID NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL,
	MESSAGE TEXT,
	STATUS OFFER_STATUS NOT NULL DEFAULT 'Pending',
	COUNTER_PRICE DECIMAL(10, 2),
	COUNTER_MESSAGE TEXT,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT FK_OFFERS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES MARKETPLACE.SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
	CONSTRAINT FK_OFFERS_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE CASCADE,
	CONSTRAINT UNIQUE_PROVIDER_REQUEST UNIQUE (REQUEST_ID, PROVIDER_ID)
);

ALTER TABLE MARKETPLACE.SERVICE_REQUESTS
ADD CONSTRAINT FK_SERVICE_REQUESTS_ACCEPTED_OFFER FOREIGN KEY (ACCEPTED_OFFER_ID) REFERENCES MARKETPLACE.OFFERS (OFFER_ID) ON DELETE SET NULL;

CREATE TABLE MARKETPLACE.REVIEWS (
	REVIEW_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	REQUEST_ID UUID NOT NULL UNIQUE,
	CUSTOMER_ID UUID NOT NULL,
	PROVIDER_ID UUID NOT NULL,
	RATING INT NOT NULL CHECK (RATING BETWEEN 1 AND 5),
	COMMENT TEXT,
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT FK_REVIEWS_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES MARKETPLACE.SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
	CONSTRAINT FK_REVIEWS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE CASCADE,
	CONSTRAINT FK_REVIEWS_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE CASCADE
);

CREATE TABLE MARKETPLACE.AUDIT_LOGS (
	AUDIT_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	USER_ID UUID,
	ACTION VARCHAR(100) NOT NULL,
	ENTITY_TYPE VARCHAR(50),
	ENTITY_ID UUID,
	DETAILS TEXT,
	IP_ADDRESS VARCHAR(45),
	CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT FK_AUDIT_LOGS_USER FOREIGN KEY (USER_ID) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE SET NULL
);

CREATE TABLE MARKETPLACE.STATUS_HISTORY (
	STATUS_HISTORY_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
	REQUEST_ID UUID NOT NULL,
	OLD_STATUS REQUEST_STATUS,
	NEW_STATUS REQUEST_STATUS NOT NULL,
	DURATION_SECONDS INT,
	CHANGED_BY UUID,
	NOTES TEXT,
	CHANGED_AT TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT FK_STATUS_HISTORY_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES MARKETPLACE.SERVICE_REQUESTS (REQUEST_ID) ON DELETE CASCADE,
	CONSTRAINT FK_STATUS_HISTORY_CHANGED_BY FOREIGN KEY (CHANGED_BY) REFERENCES MARKETPLACE.USERS (USER_ID) ON DELETE SET NULL
);